appName: petclinic-config-server
env: dev
image:
  repository: ktei8htop15122004/clinic-microservice
  tag: config-server-3e746fa
  pullSecret: dockerhub
  pullPolicy: Always
service:
  port: 8888
  type: ClusterIP

configMap:
  configServer:
    create: true
  name: petclinic-config-server-application-properties-configmap

ingress:
  domainName: config-server-dev.khacthienit.click
  path: /
  pathType: Prefix
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"