apiVersion: v2
name: api-gateway
description: A Helm chart for Spring Cloud API Gateway in PetClinic microservices
type: application

# Chart version (follows SemVer)
version: 1.0.0


appVersion: latest

dependencies:
  - name: common
    version: 1.0.0
    repository: "file://../common"